apiVersion: v1
kind: Pod
metadata:
  name: lab-pod
  labels:
    app: lab-pod-app
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Mensaje Actualizado v2.0
    image: quay.io/practicalopenshift/hello-world
    imagePullPolicy: Always
    name: hello-world-override
    resources: {}
